
Gero

Gero -> goals

goals.one
goals.two
goals.three

goals: {
    style.fill : lightblue
    style.fill-pattern : lines
}

Gero -> responsabilities

responsabilities.gf
responsabilities.family
responsabilities.job

responsabilities: {
    style.fill : "#f45346"
    style.fill-pattern : lines
}